# Generated by Django 5.1.6 on 2025-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('job_title', models.CharField(max_length=255, verbose_name='عنوان شغلی')),
                ('button_text', models.CharField(max_length=100, verbose_name='متن دکمه')),
                ('avatar', models.ImageField(upload_to='hero/', verbose_name='تصویر آواتار')),
            ],
        ),
    ]
