# Generated by Django 5.1.6 on 2025-02-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('svg_code', models.TextField(verbose_name='کد SVG')),
            ],
            options={
                'verbose_name': 'ویژگی ها',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'اطلاعات شخصی', 'verbose_name_plural': 'اطلاعات شخصی'},
        ),
    ]
