# Generated by Django 5.1.6 on 2025-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_feature_alter_herosection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(max_length=300, verbose_name='توضیحات'),
        ),
    ]
