# Generated by Django 5.1.6 on 2025-02-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_feature_options_alter_feature_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('position', models.CharField(max_length=50, verbose_name='سطح')),
                ('freelancer_status', models.BooleanField(default=True, verbose_name='فریلنسر')),
                ('exprience_years', models.PositiveIntegerField(verbose_name='سال های سابقه کار')),
                ('about_title', models.CharField(max_length=150, verbose_name='عنوان درباره من')),
                ('about_description', models.TextField(verbose_name='توضیحات درباره من')),
                ('cv_file', models.FileField(upload_to='cv_file/', verbose_name='فایل رزومه')),
                ('main_image', models.ImageField(upload_to='about/', verbose_name='تصویر اصلی')),
                ('thumb_image', models.ImageField(upload_to='about/thumb', verbose_name='تصویر کوچک')),
                ('ribbon_image', models.ImageField(upload_to='about/ribbon', verbose_name='تصویر نشان')),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'تنظیمات درباره من',
            },
        ),
    ]
