# Generated by Django 5.1.6 on 2025-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بخش')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('percentage', models.PositiveIntegerField(verbose_name='درصد مهارت')),
            ],
            options={
                'verbose_name': 'مهارت ها',
                'verbose_name_plural': 'تنظیمات مهارت ها',
            },
        ),
        migrations.AlterField(
            model_name='counter',
            name='speed',
            field=models.IntegerField(default=2000, verbose_name='سرعت'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='value',
            field=models.PositiveIntegerField(verbose_name='مقدار'),
        ),
    ]
