# Generated by Django 5.1.6 on 2025-02-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_skill_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.TextField(verbose_name='آیکون به صورت SVG')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'تنظیمات خدمات',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'تنظیمات ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'اطلاعات شخصی', 'verbose_name_plural': 'تنظیمات اطلاعات شخصی'},
        ),
    ]
