# Generated by Django 5.1.6 on 2025-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_service_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExpreience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'تنظیمات سابقه کاری',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
