# Generated by Django 5.1.6 on 2025-02-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_workexpreience_alter_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='عنوان رشته')),
                ('univercity', models.CharField(max_length=100, verbose_name='نام دانشگاه')),
                ('start_year', models.IntegerField(verbose_name='سال شروع تحصیل')),
                ('end_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='سال پایانی تحصیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سابقه تحصیلی',
                'verbose_name_plural': 'تنظیمات سابقه تحصیلی',
            },
        ),
        migrations.AlterField(
            model_name='workexpreience',
            name='company',
            field=models.CharField(max_length=100, verbose_name='اسم شرکت'),
        ),
        migrations.AlterField(
            model_name='workexpreience',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workexpreience',
            name='end_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سال پایان فعالیت'),
        ),
        migrations.AlterField(
            model_name='workexpreience',
            name='position',
            field=models.CharField(max_length=100, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='workexpreience',
            name='start_year',
            field=models.IntegerField(verbose_name='سال شروع فعالیت'),
        ),
    ]
