# Generated by Django 5.1.6 on 2025-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_protfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protfolioitem',
            name='category',
            field=models.CharField(choices=[('سایبر آموز', 'CyberAmooz')], max_length=50, verbose_name='دسته بندی'),
        ),
    ]
