# Generated by Django 5.1.6 on 2025-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_protfolioitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocailMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(verbose_name='لینک تلگرام')),
                ('youtube', models.URLField(verbose_name='لینک یوتیوب')),
                ('github', models.URLField(verbose_name='لینک گیت هاب')),
                ('instagram', models.URLField(verbose_name='لینک اینستاگرام')),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'تنظیمات شبکه های اجتماعی',
            },
        ),
    ]
