# Generated by Django 5.1.6 on 2025-02-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_socailmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protfolioitem',
            name='category',
            field=models.CharField(choices=[('سایبر آموز', 'CyberAmooz'), ('تدریس', 'techear')], max_length=50, verbose_name='دسته بندی'),
        ),
    ]
