# Generated by Django 5.1.6 on 2025-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_protfolioitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('category', models.CharField(max_length=100, verbose_name='دسته بندی')),
                ('date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnails', verbose_name='تصویر')),
                ('main_image', models.ImageField(upload_to='blog/images', verbose_name='تصویر اصلی')),
                ('content', models.TextField(verbose_name='متن مقاله')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'تنظیمات پست وبلاگ',
            },
        ),
    ]
