# Generated by Django 5.1.6 on 2025-02-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_contactinfo_contactmessage_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'عضویت ایمیلی',
                'verbose_name_plural': 'مدیریت عضویت ایمیلی',
            },
        ),
    ]
